import Head from "next/head";
import Image from "next/image";
import "dayjs/locale/ja";
import { css } from "@emotion/react";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import dayjs from "dayjs";
import { useRouter } from "next/router";
import RelationSanku from "public/relation_sanku.png";
import RelationYado from "public/relation_yado.png";
import { CalendarInfo } from "@/entities/CalendarInfo";

const BREAKPOINT = "@media (max-width: 755px)";

const ASTROLOGY27 = [
  "昴宿",
  "畢宿",
  "觜宿",
  "参宿",
  "井宿",
  "鬼宿",
  "柳宿",
  "星宿",
  "張宿",
  "翼宿",
  "軫宿",
  "角宿",
  "亢宿",
  "氐宿",
  "房宿",
  "心宿",
  "尾宿",
  "箕宿",
  "斗宿",
  "女宿",
  "虚宿",
  "危宿",
  "室宿",
  "壁宿",
  "奎宿",
  "婁宿",
  "胃宿",
];

export default function Result() {
  const router = useRouter();
  const [myShukuyou, setShukuyou] = useState(router.query.syukuyou as string);
  const rotateAngle = ASTROLOGY27.indexOf(myShukuyou) * 13.35;

  useEffect(() => {}, []);

  return (
    <>
      <Head>
        <title>{myShukuyou}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>{myShukuyou}</div>
        <div>
          <Image
            css={css`
              position: absolute;
              margin-left: auto;
              margin-right: auto;
            `}
            src={RelationSanku}
            alt="relation_sanku"
          />
          <Image
            css={css`
              transform: rotate(${rotateAngle}deg);
            `}
            src={RelationYado}
            alt="relation_yado"
          />
        </div>
      </main>
    </>
  );
}
